CMD_ALIASES:
  [
    { name: "play", aliases: ["p", "pl"] },
    { name: "help", aliases: ["h", "hlp"] },
    { name: "stop", aliases: ["stp"] },
    { name: "credits", aliases: ["c"] },
    { name: "profile", aliases: ["pf"] },
  ]
BOT:
  ACTIVITYS: { name: "/help", type: "COMPETING" }
  STATUS: "idle"
  TOKEN: "OTcwMzUwNTUxOTYxMzA5MjM1.GX8sU2.TU_B84wOd476U7Mk5W3amka-DcMUtO-hsaYFt4"
  PREFIX: "."
  lavalink:
    {
      host: "node1.kartadharta.xyz",
      password: "kdlavalink",
      secure: true,
      port: 443,
    }
REPLYS:
  videoNOT: "ğŸ¥ new video!!! {videoName} ( {videoURL} )"
  en:
    noPerms: "ğŸš« | You don't have permissions to acess This command."
    langChange: "ğŸ“œ | The bot language has been changed from `english` to `arabic`"
    noArg: "ğŸš« | There is a missing entry that you should include next to the command: `{arg}`."
    noArgC: "ğŸš« | This option have to be one of these: `{c}`."
    doneBAN: "âœˆ | {userTAG}, got banned , reason: `{reason}`"
    errBAN: "ğŸš« | I can't ban this member sadly."
    doneKICK: "âœˆ | {userTAG}, got kicked , reason: `{reason}`"
    errKICK: "ğŸš« | I can't kick this member sadly."
    unbanDONE: "ğŸ›¬ | {userTAG}, Has been unbaned."
    unbanNOTfind: "ğŸš« | I can't find this user in the ban list."
    unbanERR: "ğŸš« | I can't unban this user for some reasons."
    doneNICK: "ğŸ“œ | Done change the nickname for `{userUsername}` to `{nickname}`."
    errNICK: "ğŸš« | I can't change nickname for some reasons."
    doneMUTE: "ğŸ”‡ | {userTAG} Has been muted for `{time}`."
    errMUTE: "ğŸš« | I can't mute this user for some reasons."
    doneUNMUTE: "ğŸ”Š | {userTAG} Has unmuted."
    errUNMUTE: "ğŸš« | I can't unmute this user for some reasons."
    cantROLE: "ğŸš« | I can't find this role sadly."
    cantROLE2: "ğŸš« | I can't find this user sadly."
    undefinedAction: "ğŸš« | Undefined action [add, remove]"
    muteHIMself: "ğŸš« | You can't mute your self."
    doneROLING: "ğŸ“œ | Action has been taken `{action}` with object `{who}` on the role `{role}`"
    doneLOCK: "ğŸ”’ | Channel has been locked."
    doneUNLOCK: "ğŸ”“ | Channel has been unlocked"
    slowDONE: "ğŸŒ | Slow mode time has  changed."
    colorDOne: "ğŸ¨ | The role color has changed."
    mc1: ":no_entry_sign: You must join a voice channel to use that!"
    mc2: ":no_entry_sign: You must be listening in ${botVoiceChannel.name} to use that!"
    mc3: ":notes: Resumed {songName}"
    mc4: ":notes: {songName} Added to ProQueue (`{time}`)!"
    mc5: ":no_entry_sign: There must be music playing to use that!"
    mc6: ":bulb: The player is already paused! Use `/resume to` unpause!"
    mc7: ":notes: Paused {songName} Type `/play` to unpause!"
    mc8: ":bulb: The player is not paused! Use `/pause` to pause!"
    mc9: ":notes: Resumed {songName}"
    mc10: ":x: bot is not currently playing."
    mc11: ":notes: Repeat Mode: {mode}"
    mc12: ":no_entry_sign: Please include a query."
    mc13: ":notes: The player has stopped and the queue has been cleared."
    mc14: ":notes: Skipped {songName} - <@!{reqID}>"
    mc15: ":no_entry_sign: Volume must be a valid integer between 0 and 150!"
    mc16: ":loud_sound: Volume changed from `{songVol}` to `{vol}`"
    doneSHOW: "ğŸ‘ | Channel on view."
    doneHIDE: "ğŸ‘ | Channel on hiden."
    FILES_ONLY: "ğŸ–¼ | this channel has been set as files-only"
    FILES_ONLY_DEL: "ğŸ–¼ | files-only channel has been deleted"
    emojiADD: "ğŸƒ | Done Added {emoji} Emoji In Your Server"
    preCOLORS: "ğŸ•‘ | Preparing your server color rules ..."
    doneCOLORS: "âœ… | Your colors is ready"
    noCOLOR: "ğŸš« | There is no color with this number."
    doCOLOR: "ğŸ¨ | your color has changed."
    doneDisableLS: "ğŸ’¹ | Leveling system is `{status}`."
    LSCupdated: "ğŸ’¹ | Levling channel has updated."
    LSMupdate: "ğŸ’¹ | Levling message has updated."
    notAlevel: "ğŸš« | The level must be a number."
    rewardIsHere: "ğŸš« | This reward is already in the database."
    updateRewards: "ğŸ’¹ | Rewards list data has been updated."
    reLS: "ğŸ’¹ | Server members points has been reseted."
    cmdOptionsNana: "ğŸš« | All command options have to be numbers."
    clearDone: "ğŸ§¹ | Deleting Messages is on Progress..."
    doneMakedARes: "ğŸ¤– | Done set the auto responce."
    doneDeleteARes: "ğŸ¤– | Done delete the auto responce."
    doneUpdateARole: "ğŸ¤– | Done update the auto role for members."
    doneDeleteARole: "ğŸ¤– | Done delete the auto role."
    doneLINE: "ğŸ¤– | Done set line in this channel."
    deleLINE: "ğŸ¤– | Done delete the line in this channel."
    cantBanurSelf: "ğŸš« | You can't ban your self."
    cantKickurSelf: "ğŸš« | You can't kick your self."
    urcredits: ":bank: | {user.username}, your account balance is `${credits}`"
    transFrWOOO: "ğŸš« | {author.username}, transfer for who??"
    urCisGant: "ğŸš« | {author.username}, You don't have any credits in your account!"
    cmjdiehu: "ğŸš« | {author.username}, Your balance is not enough for that!"
    onlyNUMMMS: "ğŸš« | {author.username}, Only numbers!"
    nowooordsa: "ğŸš« | {user.username}, Type a Amount `Not Negative`"
    doneTrans: ":moneybag: | {author.username}, has transferred `${amount}` to {user}"
    prefixChange: "ğŸ”§ | Bot prefix has been changed to `{pref}`"
    coolDown: "â° | You are in cooldown {time}"
    doneTempChannelCreated: "ğŸ”Š | Temp channels has been created."
    marwaaaaaaaaaaaaanPabloooooooooooo: "ğŸ•³ | Mention welcomer has enabled."

    ban_kickREASONS:
      [
        { label: "Spam", value: "Spam" },
        { label: "Swaering", value: "Swaering" },
        { label: "Scam", value: "Scam" },
        { label: "Hacking", value: "Hacking" },
        { label: "Bitching", value: "Bitching" },
      ]
  ar:
    noPerms: "ğŸš« | Ù„ÙŠØ³ Ù„Ø¯ÙŠÙƒ ØµÙ„Ø­ÙŠØ§Øª Ù„Ø£Ø³ØªØ®Ø¯Ø§Ù… Ù‡Ø°Ø§ Ø§Ù„Ø£Ù…Ø±."
    langChange: "ğŸ“œ | ØªÙ… ØªØºÙŠØ± Ù„ØºØ© Ø§Ù„Ø¨ÙˆØª Ù…Ù† `Ø¹Ø±Ø¨ÙŠ` Ø§Ù„Ù‰ `Ø§Ù†Ø¬Ù„ÙŠØ²ÙŠ`"
    noArg: "ğŸš« | ÙŠÙˆØ¬Ø¯ Ø¥Ø¯Ø®Ø§Ù„ Ù…ÙÙ‚ÙˆØ¯ ÙŠØ¬Ø¨ Ø¹Ù„ÙŠÙƒ ØªØ¶Ù…ÙŠÙ†Ù‡ Ø¨Ø¬ÙˆØ§Ø± Ø§Ù„Ø£Ù…Ø±: `{arg}`."
    doneBAN: "âœˆ | {userTAG}, Ù‚Ø¯ ØªÙ… Ø­Ø¸Ø±Ø© , Ø§Ù„Ø³Ø¨Ø¨: `{reason}`"
    errBAN: "ğŸš« | Ù„Ø§ ÙŠÙ…ÙƒÙ†Ù†ÙŠ Ø­Ø¸Ø± Ù‡Ø°Ø§ Ø§Ù„Ø´Ø®Øµ Ù„Ø¨Ø¹Ø¶ Ø§Ù„Ø£Ø³Ø¨Ø§Ø¨.."
    doneKICK: "âœˆ | {userTAG}, Ù‚Ø¯ ØªÙ… Ø·Ø±Ø¯Ø© , Ø§Ù„Ø³Ø¨Ø¨: `{reason}`"
    errKICK: "ğŸš« | Ù„Ø§ ÙŠÙ…ÙƒÙ†Ù†ÙŠ Ø·Ø±Ø¯ Ù‡Ø°Ø§ Ø§Ù„Ø´Ø®Øµ Ù„Ø¨Ø¹Ø¶ Ø§Ù„Ø£Ø³Ø¨Ø§Ø¨."
    unbanDONE: "ğŸ›¬ | {userTAG}, Ù‚Ø¯ Ø­Ø²Ù Ù…Ù† Ù‚Ø§Ø¦Ù…Ø© Ø§Ù„Ù…Ø­Ø¸ÙˆØ±ÙŠÙ†"
    unbanNOTfind: "ğŸš« | Ø§Ù†Ø§ Ù„Ø§ Ø§Ø¬Ø¯ Ù‡Ø°Ø§ Ø§Ù„Ø´Ø®Øµ Ø¹Ù„Ù‰ Ù‚Ø§Ø¦Ù…Ø© Ø§Ù„Ø­Ø¸ÙˆØ±ÙŠÙ†"
    unbanERR: "ğŸš« | Ù„Ø§ ÙŠÙ…ÙƒÙ†Ù†ÙŠ ÙÙƒ Ø§Ù„Ø­Ø¸Ø± Ø¹Ù† Ù‡Ø°Ø§ Ø§Ù„Ø´Ø®Øµ Ù„Ø¨Ø¹Ø¶ Ø§Ù„Ø£Ø³Ø¨Ø§Ø¨."
    doneNICK: "ğŸ“œ | ØªÙ… ØªØºÙŠØ± Ø§Ø³Ù… `{userUsername}` Ù„ `{nickname}`"
    errNICK: "ğŸš« | Ù„Ø§ ÙŠÙ…ÙƒÙ†Ù†ÙŠ ØªØºÙŠØ± Ø§Ø³Ù… Ù‡Ø°Ø§ Ø§Ù„Ø´Ø®Øµ Ù„Ø¨Ø¹Ø¶ Ø§Ù„Ø£Ø³Ø¨Ø§Ø¨."
    doneMUTE: "ğŸ”‡ | {userTAG} ØªÙ… Ø§Ø³ÙƒØ§ØªÙ‡ Ù„Ù…Ø¯Ø© `{time}`."
    errMUTE: "ğŸš« | Ù„Ø§ ÙŠÙ…ÙƒÙ†Ù†ÙŠ Ø§Ø³ÙƒØ§Øª Ù‡Ø°Ø§ Ø§Ù„Ø´Ø®Øµ Ù„Ø¨Ø¹Ø¶ Ø§Ù„Ø£Ø³Ø¨Ø§Ø¨.."
    doneUNMUTE: "ğŸ”Š | {userTAG} ØªÙ… ÙÙƒ Ø§Ø³ÙƒØ§ØªÙ‡."
    errUNMUTE: "ğŸš« | Ù„Ø§ ÙŠÙ…ÙƒÙ†Ù†ÙŠ ÙÙƒ Ø§Ø³ÙƒØ§Øª Ù‡Ø°Ø§ Ø§Ù„Ø´Ø®Øµ Ù„Ø¨Ø¹Ø¶ Ø§Ù„Ø£Ø³Ø¨Ø§Ø¨.."
    cantROLE: "ğŸš« | Ù„Ø§ ÙŠÙ…ÙƒÙ†Ù†ÙŠ Ø§Ù„Ø¹Ø«ÙˆØ± Ø¹Ù„Ù‰ Ù‡Ø°Ù‡ Ø§Ù„Ø±ØªØ¨Ø© Ø§Ù„Ù„Ø¹ÙŠÙ†Ù‡."
    cantROLE2: "ğŸš« | Ù„Ø§ ÙŠÙ…ÙƒÙ†Ù†ÙŠ Ø§Ù„Ø¹Ø«ÙˆØ± Ø¹Ù„Ù‰ Ù‡Ø°Ø§ Ø§Ù„Ø´Ø®Øµ Ø§Ù„Ù„Ø¹ÙŠÙ†."
    doneROLING: "ğŸ“œ | ØªÙ… Ø§ØªØ®Ø§Ø² Ø§Ø¬Ø±Ø§Ø¡ `{action}` Ù…Ø¹ Ø§Ù„Ø¹Ù†ØµØ± `{who}` Ø¹Ù„Ù‰ Ø§Ù„Ø±ØªØ¨Ø© `{role}`"
    undefinedAction: "ğŸš« | Ø§Ù„Ø£Ø¬Ø±Ø§Ø¡ ØºÙŠØ± Ù…Ø¹Ø±ÙˆÙ [add, remove]"
    doneLOCK: "ğŸ”’ | ØªÙ… Ø§ØºÙ„Ø§Ù‚ Ø§Ù„ØºØ±ÙØ©."
    doneUNLOCK: "ğŸ”“ | ØªÙ… ÙØªØ­ Ø§Ù„ØºØ±ÙØ©."
    slowDONE: "ğŸŒ | ÙˆØ¶Ø¹ Ø§Ù„Ø£Ø¨Ø·Ø§Ø¡ ØªÙ… ØªØºÙŠØ±Ù‡."
    colorDOne: "ğŸ¨ | ØªÙ… ØªØºÙŠØ± Ù„ÙˆÙ† Ø§Ù„Ø±ØªØ¨Ø©."
    mc1: ":no_entry_sign: ÙŠØ¬Ø¨ Ø§Ù† ØªÙƒÙˆÙ† ÙÙŠ ØºØ±ÙØ© ØµÙˆØªÙŠØ© Ù„Ø£Ø³ØªØ®Ø¯Ø§Ù… Ù‡Ø°Ø§ Ø§Ù„Ø£Ù…Ø±!"
    mc2: ":no_entry_sign: Ø¹Ù„ÙŠÙƒ Ø§Ù† ØªÙ†Ø¶Ù… Ù„Ù€ ${botVoiceChannel.name} Ù„Ø£Ø³ØªØ®Ø¯Ø§Ù… Ù‡Ø°Ø§ Ø§Ù„Ø£Ù…Ø±!"
    mc3: ":notes: Ù…Ø³ØªØ£Ù†Ù {songName}"
    mc4: ":notes: {songName} ØªÙ…Øª Ø¥Ø¶Ø§ÙØªÙ‡ Ø¥Ù„Ù‰ Queue (`{time}`)!"
    mc5: ":no_entry_sign: ÙŠØ¬Ø¨ Ø£Ù† ÙŠÙƒÙˆÙ† Ù‡Ù†Ø§Ùƒ ØªØ´ØºÙŠÙ„ Ø§Ù„Ù…ÙˆØ³ÙŠÙ‚Ù‰ Ù„Ø§Ø³ØªØ®Ø¯Ø§Ù… Ù‡Ø°Ø§ Ø§Ù„Ø£Ù…Ø±!"
    mc6: ":bulb: Ù…Ø´ØºÙ„ Ø§Ù„Ø£ØºØ§Ù†ÙŠ ØªÙ… Ø§ÙŠÙ‚Ø§ÙÙ‡ Ù…Ø³Ø¨Ù‚Ø§Ù! Ø§Ø³ØªØ¹Ù…Ù„ `/resume to` Ù„Ø£Ù„ØºØ§Ø¡ Ø§ÙŠÙ‚Ø§ÙÙ‡!"
    mc7: ":notes: Ù…ØªÙˆÙ‚Ù Ù…Ø¤Ù‚ØªÙ‹Ø§ {songName} Ø§Ø³ØªØ¹Ù…Ù„ `/play` Ù„Ù„Ø£Ø³ØªÙƒÙ…Ø§Ù„!"
    mc8: ":bulb: Ù…Ø´ØºÙ„ Ø§Ù„Ø£ØºØ§Ù†ÙŠ ÙŠØ¹Ù…Ù„ Ø¨Ø§Ù„ÙØ¹Ù„! Ø§Ø³ØªØ¹Ù…Ù„ `/pause` Ù„Ù„ØªÙˆÙ‚Ù!"
    mc9: ":notes: Ù…Ø³ØªØ£Ù†Ù {songName}"
    mc10: ":x: Ø§Ù„Ù†Ø¸Ø§Ù… Ù„Ø§ ÙŠÙ„Ø¹Ø¨ Ø§ÙŠ Ø§ØºÙ†ÙŠÙ‡."
    mc11: ":notes: ÙˆØ¶Ø¹ Ø§Ù„ØªÙƒØ±Ø§Ø±: {mode}"
    mc12: ":no_entry_sign: ÙŠØ¤Ø¬Ù‰ Ø§Ø±ÙØ§Ù‚ ÙƒÙ„Ù…Ø© Ù„Ù„Ø¨Ø­Ø«."
    mc13: ":notes: Ù‚Ø¯ ØªÙˆÙ‚Ù Ù†Ø¸Ø§Ù… ØªØ´ØºÙŠÙ„ Ø§Ù„Ø£ØºØ§Ù†ÙŠ Ùˆ Ø­Ø²Ù Ø·Ø§Ø¨ÙˆØ± Ø§Ù„Ø£ØºØ§Ù†ÙŠ."
    mc14: ":notes: ØªØ®Ø·ÙŠ {songName} - <@!{reqID}>"
    mc15: ":no_entry_sign: ÙŠØ¬Ø¨ Ø£Ù† ÙŠÙƒÙˆÙ† Ù…Ø³ØªÙˆÙ‰ Ø§Ù„ØµÙˆØª Ø¹Ø¯Ø¯Ù‹Ø§ ØµØ­ÙŠØ­Ù‹Ø§ ÙŠØªØ±Ø§ÙˆØ­ Ø¨ÙŠÙ† 0 Ùˆ 150!"
    mc16: ":loud_sound: ØªÙ… ØªØºÙŠÙŠØ± Ù…Ø³ØªÙˆÙ‰ ØµÙˆØª Ø§Ù„Ù…ÙˆØ³ÙŠÙ‚Ù‰ Ù…Ù† `{songVol}` Ù„Ù€ `{vol}`"
    doneSHOW: "ğŸ‘ | Ø§Ù„Ù‚Ù†Ø§Ø© Ù…Ø¹Ø±ÙˆØ¶Ø©."
    doneHIDE: "ğŸ‘ | Ø§Ù„Ù‚Ù†Ø§Ù‡ Ù…Ø®ÙÙŠØ©."
    FILES_ONLY: "ğŸ–¼ | Ù‡Ø°Ù‡ Ø§Ù„Ù‚Ù†Ø§Ø© Ø¹ÙŠÙ†Ø© Ù„Ù„Ù…Ù„ÙØ§Øª Ùˆ Ø§Ù„ØµÙˆØ± ÙÙ‚Ø·"
    FILES_ONLY_DEL: "ğŸ–¼ | ØºØ±ÙØ© Ø§Ù„Ù…Ù„ÙØ§Øª Ù‚Ø¯ Ø­Ø²ÙØª"
    emojiADD: "ğŸƒ | ØªÙ… Ø§Ø¶Ø§ÙØ© Ø§Ù„Ø£ÙŠÙ…ÙˆØ¬ÙŠ {emoji} Ù„Ù„Ø®Ø§Ø¯Ù…"
    preCOLORS: "ğŸ•‘ | Ø¬Ø§Ø±ÙŠ ØªØ¬Ù‡ÙŠØ² Ø§Ù„ÙˆØ§Ù† Ø®Ø§Ø¯Ù…Ùƒ ..."
    doneCOLORS: "âœ… | Ø§Ù„ÙˆØ§Ù†Ùƒ Ø¬Ø§Ù‡Ø²Ù‡"
    noCOLOR: "ğŸš« | Ù„Ø§ ÙŠÙˆØ¬Ø¯ Ù„ÙˆÙ† Ø¨Ù‡Ø§Ø°Ø§ Ø§Ù„Ø±Ù‚Ù…."
    doCOLOR: "ğŸ¨ | ØªÙ… ØªØºÙŠØ± Ù„ÙˆÙ†Ùƒ."
    doneDisableLS: "ğŸ’¹ | Ù†Ø¸Ø§Ù… Ø§Ù„Ù…Ø³ØªÙˆÙ‰ `{status}`."
    LSCupdated: "ğŸ’¹ | Ù‚Ù†Ø§Ø© Ø§Ø´Ø¹Ø§Ø±Ø§Øª Ø§Ù„Ù…Ø³ØªÙˆÙ‰. Ù‚Ø¯ ØªÙ… ØªØºÙŠØ±Ù‡Ø§."
    LSMupdate: "ğŸ’¹ | Ø±Ø³Ø§Ù„Ø© Ø§Ø´Ø¹Ø§Ø±Ø§Øª Ø§Ù„Ù…Ø³ØªÙˆÙ‰. Ù‚Ø¯ ØªØºÙŠØ±Øª."
    notAlevel: "ğŸš« | Ø§Ù„Ù…Ø³ØªÙˆÙ‰ ÙŠØ¬Ø¨ Ø§Ù† ÙŠÙƒÙˆÙ† Ø±Ù‚Ù… ØµØ­ÙŠØ­."
    rewardIsHere: "ğŸš« | Ù‡Ø°Ù‡ Ø§Ù„Ø¬Ø§Ø¦Ø²Ù‡ Ù…ÙˆØ¬ÙˆØ¯Ù‡ Ø¨Ù„ÙØ¹Ù„ ÙÙŠ Ù‚Ø§Ø¹Ø¯Ø© Ø§Ù„Ø¨Ø§Ù†Ø§Øª."
    updateRewards: "ğŸ’¹ | Ù‚Ø§Ø¦Ù…Ø© Ø¬ÙˆØ§Ø¦Ø² Ø§Ù„Ù…Ø³ØªÙˆÙ‰. Ù‚Ø¯ Ø¹Ø¯Ù„Øª."
    reLS: "ğŸ’¹ | ÙƒÙ„ Ù†Ù‚Ø§Ø· Ø§Ù„Ù…Ø³ØªÙˆÙ‰ Ù‚Ø¯ ØªÙ… ØªØµÙÙŠØ±Ù‡Ø§."
    cmdOptionsNana: "ğŸš« | ÙƒÙ„ Ø§Ø®ØªÙŠØ§Ø±Ø§Øª Ø§Ù„Ø£Ù…Ø± ÙŠØ¬Ø¨ Ø§Ù† ØªÙƒÙˆÙ† Ø§Ø±Ù‚Ø§Ù… ØµØ­ÙŠØ­Ù‡."
    clearDone: "ğŸ§¹ | Ø­Ø²Ù Ø§Ù„Ø±Ø³Ø§Ø¦Ù„ Ù‚Ø§ÙŠØ¯ Ø§Ù„ØªÙ‚Ø¯Ù…..."
    doneMakedARes: "ğŸ¤– | ØªÙ… ÙˆØ¶Ø¹ Ø§Ù„Ø±Ø¯ Ø§Ù„ØªÙ„Ù‚Ø§Ø¦ÙŠ."
    doneDeleteARes: "ğŸ¤– | ØªÙ… Ø­Ø²Ù Ø§Ù„Ø±Ø¯ Ø§Ù„ØªÙ„Ù‚Ø§Ø¦ÙŠ."
    doneUpdateARole: "ğŸ¤– | ØªÙ… ØªØ¹Ø¯ÙŠÙ„ Ø§Ù„Ø±ØªØ¨Ø© Ø§Ù„ØªÙ„Ù‚Ø§Ø¦ÙŠÙ‡ Ù„Ù„Ø£Ø¹Ø¶Ø§Ø¡."
    doneDeleteARole: "ğŸ¤– | ØªÙ… Ø­Ø²Ù Ø§Ù„Ø±ØªØ¨Ø© Ø§Ù„ØªÙ„Ù‚Ø§Ø¦ÙŠÙ‡ Ù„Ù„Ø£Ø¹Ø¶Ø§Ø¡."
    doneLINE: "ğŸ¤– | ØªÙ… ÙˆØ¶Ø¹ Ø§Ù„Ø®Ø· ÙÙŠ Ù‡Ø°Ù‡ Ø§Ù„Ù‚Ù†Ø§Ø©"
    deleLINE: "ğŸ¤– | ØªÙ… Ø­Ø²Ù Ø§Ù„Ø®Ø· Ù…Ù† Ø§Ù„Ù‚Ù†Ø§Ù‡"
    cantBanurSelf: "ğŸš« | Ù„Ø§ ÙŠÙ…ÙƒÙ†Ùƒ Ø­Ø¸Ø± Ù†ÙØ³Ùƒ."
    cantKickurSelf: "ğŸš« | Ù„Ø§ ÙŠÙ…ÙƒÙ†Ùƒ Ø·Ø±Ø¯ Ù†ÙØ³Ùƒ."
    urcredits: ":bank: | {user.username}, Ù‚ÙŠÙ…Ø© Ø­Ø³Ø§Ø¨Ùƒ Ø§Ù„Ø­Ø§Ù„ÙŠØ© Ù‡ÙŠ `${credits}`"
    transFrWOOO: "ğŸš« | {author.username}, Ù„Ù…Ù† ØªØ±ÙŠØ¯ Ø§Ù„ØªØ­ÙˆÙŠÙ„??"
    urCisGant: "ğŸš« | {author.username}, Ø£Ù†Øª Ø¹Ù„ Ø¬Ù†Ø¸ Ù…Ù† Ø§Ù„Ø£Ø®Ø±!"
    cmjdiehu: "ğŸš« | {author.username}, ÙƒØ­ÙŠØ§Ù† Ù…Ø¹ÙƒØ´ ÙÙ„ÙˆØ³!"
    onlyNUMMMS: "ğŸš« | {author.username}, Ø§Ù„Ø£Ø±Ù‚Ø§Ù… ÙÙ‚Ø·!"
    nowooordsa: "ğŸš« | {user.username}, Ø§Ù„Ø£Ø±Ù‚Ø§Ù… Ø§Ù„Ø³Ø§Ù„Ø¨Ù‡ ØºÙŠØ± Ù…Ø­Ù‚Ù‚Ù‡"
    doneTrans: ":moneybag: | {author.username}, ØªÙ… ØªØ­ÙˆÙŠÙ„ Ù…Ø¨Ù„Øº Ø¨Ù‚ÙŠÙ…Ø© `${amount}` Ù„Ù€ {user}"
    prefixChange: "ğŸ”§ | ØªÙ… ØªØºÙŠØ± Ø¨Ø§Ø¯Ø¦Ø© Ø§Ù„Ø¨ÙˆØª Ù„Ù€ `{pref}`"
    coolDown: "â° | Ø§Ù†Øª ØªØ­Øª ØªØ£Ø«ÙŠØ± Ø§Ù„Ø£Ø¨Ø·Ø§Ø¡ {time}"
    doneTempChannelCreated: "ğŸ”Š | ØªÙ… Ø£Ù†Ø´Ø§Ø¡ Ø§Ù„ØºØ±Ù Ø§Ù„Ù…Ø¤Ù‚ØªØ©."
    marwaaaaaaaaaaaaanPabloooooooooooo: "ğŸ•³ | ØªÙ… ØªÙØ¹Ù„ÙŠ ÙˆØ¶Ø¹ Ø§Ù„Ù…Ù†Ø´Ù† Ø§Ù„ØªØ±Ø­ÙŠØ¨ÙŠ."
    ban_kickREASONS:
      [
        { label: "Ø³Ø¨Ø§Ù…", value: "Ø³Ø¨Ø§Ù…" },
        { label: " Ø³Ø¨", value: "Ø³Ø¨" },
        { label: "Ø§Ø­ØªÙŠØ§Ù„", value: "Ø§Ø­ØªÙŠØ§Ù„" },
        { label: "Ù…Ø­Ø§ÙˆÙ„Ø© Ø§Ø®ØªØ±Ø§Ù‚", value: "Ù…Ø­Ø§ÙˆÙ„Ø© Ø§Ø®ØªØ±Ø§Ù‚" },
        { label: "ØªØ±Ù…ÙˆØªÙ‡", value: "ØªØ±Ù…ÙˆØªÙ‡" },
      ]
